*"* use this source file for the definition and implementation of
*"* local helper classes, interface definitions and type
*"* declarations
CLASS lcl_helper DEFINITION.
  PUBLIC SECTION.
    METHODS generate_mapping
      IMPORTING out TYPE REF TO if_oo_adt_classrun_out.
ENDCLASS.

CLASS lcl_helper IMPLEMENTATION.
  METHOD generate_mapping.

    DATA ldt_data TYPE STANDARD TABLE OF zw00117t_vn WITH EMPTY KEY.

    DELETE FROM zw00117t_vn WHERE mapping_code = '0001'.

    ldt_data = VALUE #(
        " ── Wrapper keys ──────────────────────────────────────────────────
        ( mapping_code = '0001' abap_field = 'payload'                      json_field = 'payload' )
        ( mapping_code = '0001' abap_field = 'approver'                     json_field = 'approver' )
        ( mapping_code = '0001' abap_field = 'requester'                    json_field = 'requester' )
        " ── Root product fields ────────────────────────────────────────────
        ( mapping_code = '0001' abap_field = 'Product'                      json_field = 'Product' )
        ( mapping_code = '0001' abap_field = 'ProductType'                  json_field = 'ProductType' )
        ( mapping_code = '0001' abap_field = 'CreationDate'                 json_field = 'CreationDate' )
        ( mapping_code = '0001' abap_field = 'CreationTime'                 json_field = 'CreationTime' )
        ( mapping_code = '0001' abap_field = 'CreationDateTime'             json_field = 'CreationDateTime' )
        ( mapping_code = '0001' abap_field = 'CreatedByUser'                json_field = 'CreatedByUser' )
        ( mapping_code = '0001' abap_field = 'LastChangeDate'               json_field = 'LastChangeDate' )
        ( mapping_code = '0001' abap_field = 'LastChangedByUser'            json_field = 'LastChangedByUser' )
        ( mapping_code = '0001' abap_field = 'IsMarkedForDeletion'          json_field = 'IsMarkedForDeletion' )
        ( mapping_code = '0001' abap_field = 'CrossPlantStatus'             json_field = 'CrossPlantStatus' )
        ( mapping_code = '0001' abap_field = 'CrossPlantStatusValidityDate' json_field = 'CrossPlantStatusValidityDate' )
        ( mapping_code = '0001' abap_field = 'ProductOldID'                 json_field = 'ProductOldID' )
        ( mapping_code = '0001' abap_field = 'GrossWeight'                  json_field = 'GrossWeight' )
        ( mapping_code = '0001' abap_field = 'WeightUnit'                   json_field = 'WeightUnit' )
        ( mapping_code = '0001' abap_field = 'ProductGroup'                 json_field = 'ProductGroup' )
        ( mapping_code = '0001' abap_field = 'BaseUnit'                     json_field = 'BaseUnit' )
        ( mapping_code = '0001' abap_field = 'ItemCategoryGroup'            json_field = 'ItemCategoryGroup' )
        ( mapping_code = '0001' abap_field = 'NetWeight'                    json_field = 'NetWeight' )
        ( mapping_code = '0001' abap_field = 'Division'                     json_field = 'Division' )
        ( mapping_code = '0001' abap_field = 'VolumeUnit'                   json_field = 'VolumeUnit' )
        ( mapping_code = '0001' abap_field = 'ProductVolume'                json_field = 'ProductVolume' )
        ( mapping_code = '0001' abap_field = 'AuthorizationGroup'           json_field = 'AuthorizationGroup' )
        ( mapping_code = '0001' abap_field = 'ANPCode'                      json_field = 'ANPCode' )
        ( mapping_code = '0001' abap_field = 'SizeOrDimensionText'          json_field = 'SizeOrDimensionText' )
        ( mapping_code = '0001' abap_field = 'IndustryStandardName'         json_field = 'IndustryStandardName' )
        ( mapping_code = '0001' abap_field = 'ProductStandardID'            json_field = 'ProductStandardID' )
        ( mapping_code = '0001' abap_field = 'InternationalArticleNumberCat' json_field = 'InternationalArticleNumberCat' )
        ( mapping_code = '0001' abap_field = 'ProductIsConfigurable'        json_field = 'ProductIsConfigurable' )
        ( mapping_code = '0001' abap_field = 'IsBatchManagementRequired'    json_field = 'IsBatchManagementRequired' )
        ( mapping_code = '0001' abap_field = 'ExternalProductGroup'         json_field = 'ExternalProductGroup' )
        ( mapping_code = '0001' abap_field = 'CrossPlantConfigurableProduct' json_field = 'CrossPlantConfigurableProduct' )
        ( mapping_code = '0001' abap_field = 'SerialNoExplicitnessLevel'    json_field = 'SerialNoExplicitnessLevel' )
        ( mapping_code = '0001' abap_field = 'IsApprovedBatchRecordReqd'    json_field = 'IsApprovedBatchRecordReqd' )
        ( mapping_code = '0001' abap_field = 'HandlingIndicator'            json_field = 'HandlingIndicator' )
        ( mapping_code = '0001' abap_field = 'WarehouseProductGroup'        json_field = 'WarehouseProductGroup' )
        ( mapping_code = '0001' abap_field = 'WarehouseStorageCondition'    json_field = 'WarehouseStorageCondition' )
        ( mapping_code = '0001' abap_field = 'StandardHandlingUnitType'     json_field = 'StandardHandlingUnitType' )
        ( mapping_code = '0001' abap_field = 'SerialNumberProfile'          json_field = 'SerialNumberProfile' )
        ( mapping_code = '0001' abap_field = 'IsPilferable'                 json_field = 'IsPilferable' )
        ( mapping_code = '0001' abap_field = 'IsRelevantForHzdsSubstances'  json_field = 'IsRelevantForHzdsSubstances' )
        ( mapping_code = '0001' abap_field = 'QuarantinePeriod'             json_field = 'QuarantinePeriod' )
        ( mapping_code = '0001' abap_field = 'TimeUnitForQuarantinePeriod'  json_field = 'TimeUnitForQuarantinePeriod' )
        ( mapping_code = '0001' abap_field = 'QualityInspectionGroup'       json_field = 'QualityInspectionGroup' )
        ( mapping_code = '0001' abap_field = 'HandlingUnitType'             json_field = 'HandlingUnitType' )
        ( mapping_code = '0001' abap_field = 'HasVariableTareWeight'        json_field = 'HasVariableTareWeight' )
        ( mapping_code = '0001' abap_field = 'MaximumPackagingLength'       json_field = 'MaximumPackagingLength' )
        ( mapping_code = '0001' abap_field = 'MaximumPackagingWidth'        json_field = 'MaximumPackagingWidth' )
        ( mapping_code = '0001' abap_field = 'MaximumPackagingHeight'       json_field = 'MaximumPackagingHeight' )
        ( mapping_code = '0001' abap_field = 'MaximumCapacity'              json_field = 'MaximumCapacity' )
        ( mapping_code = '0001' abap_field = 'OvercapacityTolerance'        json_field = 'OvercapacityTolerance' )
        ( mapping_code = '0001' abap_field = 'UnitForMaxPackagingDimensions' json_field = 'UnitForMaxPackagingDimensions' )
        ( mapping_code = '0001' abap_field = 'BaseUnitSpecificProductLength' json_field = 'BaseUnitSpecificProductLength' )
        ( mapping_code = '0001' abap_field = 'BaseUnitSpecificProductWidth'  json_field = 'BaseUnitSpecificProductWidth' )
        ( mapping_code = '0001' abap_field = 'BaseUnitSpecificProductHeight' json_field = 'BaseUnitSpecificProductHeight' )
        ( mapping_code = '0001' abap_field = 'ProductMeasurementUnit'       json_field = 'ProductMeasurementUnit' )
        ( mapping_code = '0001' abap_field = 'ArticleCategory'              json_field = 'ArticleCategory' )
        ( mapping_code = '0001' abap_field = 'IndustrySector'               json_field = 'IndustrySector' )
        ( mapping_code = '0001' abap_field = 'LastChangeDateTime'           json_field = 'LastChangeDateTime' )
        ( mapping_code = '0001' abap_field = 'LastChangeTime'               json_field = 'LastChangeTime' )
        ( mapping_code = '0001' abap_field = 'DangerousGoodsIndProfile'     json_field = 'DangerousGoodsIndProfile' )
        ( mapping_code = '0001' abap_field = 'ProductDocumentChangeNumber'  json_field = 'ProductDocumentChangeNumber' )
        ( mapping_code = '0001' abap_field = 'ProductDocumentPageCount'     json_field = 'ProductDocumentPageCount' )
        ( mapping_code = '0001' abap_field = 'ProductDocumentPageNumber'    json_field = 'ProductDocumentPageNumber' )
        ( mapping_code = '0001' abap_field = 'DocumentIsCreatedByCAD'       json_field = 'DocumentIsCreatedByCAD' )
        ( mapping_code = '0001' abap_field = 'ProductionOrInspectionMemoTxt' json_field = 'ProductionOrInspectionMemoTxt' )
        ( mapping_code = '0001' abap_field = 'ProductionMemoPageFormat'     json_field = 'ProductionMemoPageFormat' )
        ( mapping_code = '0001' abap_field = 'ProductIsHighlyViscous'       json_field = 'ProductIsHighlyViscous' )
        ( mapping_code = '0001' abap_field = 'TransportIsInBulk'            json_field = 'TransportIsInBulk' )
        ( mapping_code = '0001' abap_field = 'ProdEffctyParamValsAreAssigned' json_field = 'ProdEffctyParamValsAreAssigned' )
        ( mapping_code = '0001' abap_field = 'ProdIsEnvironmentallyRelevant' json_field = 'ProdIsEnvironmentallyRelevant' )
        ( mapping_code = '0001' abap_field = 'LaboratoryOrDesignOffice'     json_field = 'LaboratoryOrDesignOffice' )
        ( mapping_code = '0001' abap_field = 'PackagingProductGroup'        json_field = 'PackagingProductGroup' )
        ( mapping_code = '0001' abap_field = 'PackingReferenceProduct'      json_field = 'PackingReferenceProduct' )
        ( mapping_code = '0001' abap_field = 'BasicProduct'                 json_field = 'BasicProduct' )
        ( mapping_code = '0001' abap_field = 'ProductDocumentNumber'        json_field = 'ProductDocumentNumber' )
        ( mapping_code = '0001' abap_field = 'ProductDocumentVersion'       json_field = 'ProductDocumentVersion' )
        ( mapping_code = '0001' abap_field = 'ProductDocumentType'          json_field = 'ProductDocumentType' )
        ( mapping_code = '0001' abap_field = 'ProductDocumentPageFormat'    json_field = 'ProductDocumentPageFormat' )
        ( mapping_code = '0001' abap_field = 'ProdChmlCmplncRelevanceCode'  json_field = 'ProdChmlCmplncRelevanceCode' )
        ( mapping_code = '0001' abap_field = 'DiscountInKindEligibility'    json_field = 'DiscountInKindEligibility' )
        ( mapping_code = '0001' abap_field = 'ProdCompetitorCustomerNumber' json_field = 'ProdCompetitorCustomerNumber' )
        ( mapping_code = '0001' abap_field = 'ProductHierarchy'             json_field = 'ProductHierarchy' )
        ( mapping_code = '0001' abap_field = 'ProdAllocDetnProcedure'       json_field = 'ProdAllocDetnProcedure' )
        ( mapping_code = '0001' abap_field = 'CountryOfOrigin'              json_field = 'CountryOfOrigin' )
        ( mapping_code = '0001' abap_field = 'RetailArticleBrand'           json_field = 'RetailArticleBrand' )
        ( mapping_code = '0001' abap_field = 'ProductValidStartDate'        json_field = 'ProductValidStartDate' )
        ( mapping_code = '0001' abap_field = 'ContentUnit'                  json_field = 'ContentUnit' )
        ( mapping_code = '0001' abap_field = 'ProductNetContentQuantity'    json_field = 'ProductNetContentQuantity' )
        ( mapping_code = '0001' abap_field = 'ProductGrossContentQuantity'  json_field = 'ProductGrossContentQuantity' )
        ( mapping_code = '0001' abap_field = 'ProductValidEndDate'          json_field = 'ProductValidEndDate' )
        ( mapping_code = '0001' abap_field = 'AssortmentListType'           json_field = 'AssortmentListType' )
        ( mapping_code = '0001' abap_field = 'TextilePartsIsWithAnimalOrigin' json_field = 'TextilePartsIsWithAnimalOrigin' )
        ( mapping_code = '0001' abap_field = 'ProductSeasonUsageCategory'   json_field = 'ProductSeasonUsageCategory' )
        ( mapping_code = '0001' abap_field = 'BillOfMaterialIsForEmpties'   json_field = 'BillOfMaterialIsForEmpties' )
        ( mapping_code = '0001' abap_field = 'ServiceAgreement'             json_field = 'ServiceAgreement' )
        ( mapping_code = '0001' abap_field = 'ConsumptionValueCategory'     json_field = 'ConsumptionValueCategory' )
        ( mapping_code = '0001' abap_field = 'GoodsIssueUnit'               json_field = 'GoodsIssueUnit' )
        ( mapping_code = '0001' abap_field = 'RegionOfOrigin'               json_field = 'RegionOfOrigin' )
        ( mapping_code = '0001' abap_field = 'ValuationClass'               json_field = 'ValuationClass' )
        ( mapping_code = '0001' abap_field = 'SalesUnit'                    json_field = 'SalesUnit' )
        ( mapping_code = '0001' abap_field = 'ProductManufacturerNumber'    json_field = 'ProductManufacturerNumber' )
        ( mapping_code = '0001' abap_field = 'ManufacturerNumber'           json_field = 'ManufacturerNumber' )
        ( mapping_code = '0001' abap_field = 'ManufacturerPartProfile'      json_field = 'ManufacturerPartProfile' )
        ( mapping_code = '0001' abap_field = 'OwnInventoryManagedProduct'   json_field = 'OwnInventoryManagedProduct' )
        " ── _ProductValuation ─────────────────────────────────────────────
        ( mapping_code = '0001' abap_field = '_ProductValuation'            json_field = '_ProductValuation' )
        ( mapping_code = '0001' abap_field = 'ValuationArea'                json_field = 'ValuationArea' )
        ( mapping_code = '0001' abap_field = 'ValuationType'                json_field = 'ValuationType' )
        ( mapping_code = '0001' abap_field = 'PriceDeterminationControl'    json_field = 'PriceDeterminationControl' )
        ( mapping_code = '0001' abap_field = 'StandardPrice'                json_field = 'StandardPrice' )
        ( mapping_code = '0001' abap_field = 'MovingAveragePrice'           json_field = 'MovingAveragePrice' )
        ( mapping_code = '0001' abap_field = 'ProductPriceUnitQuantity'     json_field = 'ProductPriceUnitQuantity' )
        ( mapping_code = '0001' abap_field = 'InventoryValuationProcedure'  json_field = 'InventoryValuationProcedure' )
        ( mapping_code = '0001' abap_field = 'ValuationCategory'            json_field = 'ValuationCategory' )
        ( mapping_code = '0001' abap_field = 'ProductUsageType'             json_field = 'ProductUsageType' )
        ( mapping_code = '0001' abap_field = 'ProductOriginType'            json_field = 'ProductOriginType' )
        ( mapping_code = '0001' abap_field = 'IsProducedInhouse'            json_field = 'IsProducedInhouse' )
        ( mapping_code = '0001' abap_field = 'ValuationClassSalesOrderStock' json_field = 'ValuationClassSalesOrderStock' )
        ( mapping_code = '0001' abap_field = 'ProjectStockValuationClass'   json_field = 'ProjectStockValuationClass' )
        ( mapping_code = '0001' abap_field = 'Currency'                     json_field = 'Currency' )
        ( mapping_code = '0001' abap_field = 'ValuationMarginPercent'       json_field = 'ValuationMarginPercent' )
        " ── _ProductUnitOfMeasure ─────────────────────────────────────────
        ( mapping_code = '0001' abap_field = '_ProductUnitOfMeasure'        json_field = '_ProductUnitOfMeasure' )
        ( mapping_code = '0001' abap_field = 'AlternativeUnit'              json_field = 'AlternativeUnit' )
        ( mapping_code = '0001' abap_field = 'QuantityNumerator'            json_field = 'QuantityNumerator' )
        ( mapping_code = '0001' abap_field = 'QuantityDenominator'          json_field = 'QuantityDenominator' )
        ( mapping_code = '0001' abap_field = 'GlobalTradeItemNumber'        json_field = 'GlobalTradeItemNumber' )
        ( mapping_code = '0001' abap_field = 'GlobalTradeItemNumberCategory' json_field = 'GlobalTradeItemNumberCategory' )
        ( mapping_code = '0001' abap_field = 'UnitSpecificProductLength'    json_field = 'UnitSpecificProductLength' )
        ( mapping_code = '0001' abap_field = 'UnitSpecificProductWidth'     json_field = 'UnitSpecificProductWidth' )
        ( mapping_code = '0001' abap_field = 'UnitSpecificProductHeight'    json_field = 'UnitSpecificProductHeight' )
        ( mapping_code = '0001' abap_field = 'LowerLevelPackagingUnit'      json_field = 'LowerLevelPackagingUnit' )
        ( mapping_code = '0001' abap_field = 'MaximumStackingFactor'        json_field = 'MaximumStackingFactor' )
        ( mapping_code = '0001' abap_field = 'CapacityUsage'                json_field = 'CapacityUsage' )
        " ── _ProductStorage ───────────────────────────────────────────────
        ( mapping_code = '0001' abap_field = '_ProductStorage'              json_field = '_ProductStorage' )
        ( mapping_code = '0001' abap_field = 'StorageConditions'            json_field = 'StorageConditions' )
        ( mapping_code = '0001' abap_field = 'ProdTemperatureConditionCode' json_field = 'ProdTemperatureConditionCode' )
        ( mapping_code = '0001' abap_field = 'HazardousProduct'             json_field = 'HazardousProduct' )
        ( mapping_code = '0001' abap_field = 'NmbrOfGROrGISlipsToPrintQty'  json_field = 'NmbrOfGROrGISlipsToPrintQty' )
        ( mapping_code = '0001' abap_field = 'LabelType'                    json_field = 'LabelType' )
        ( mapping_code = '0001' abap_field = 'LabelForm'                    json_field = 'LabelForm' )
        ( mapping_code = '0001' abap_field = 'MinRemainingShelfLife'        json_field = 'MinRemainingShelfLife' )
        ( mapping_code = '0001' abap_field = 'ProductExpirationDateType'    json_field = 'ProductExpirationDateType' )
        ( mapping_code = '0001' abap_field = 'StorageBinInstruction'        json_field = 'StorageBinInstruction' )
        ( mapping_code = '0001' abap_field = 'ShelfLifeExpirationDatePeriod' json_field = 'ShelfLifeExpirationDatePeriod' )
        ( mapping_code = '0001' abap_field = 'ShelfLifeExprtnDateRndngRule'  json_field = 'ShelfLifeExprtnDateRndngRule' )
        ( mapping_code = '0001' abap_field = 'TotalShelfLifeStoragePercent'  json_field = 'TotalShelfLifeStoragePercent' )
        ( mapping_code = '0001' abap_field = 'TotalShelfLife'               json_field = 'TotalShelfLife' )
        " ── _ProductSalesDelivery ─────────────────────────────────────────
        ( mapping_code = '0001' abap_field = '_ProductSalesDelivery'        json_field = '_ProductSalesDelivery' )
        ( mapping_code = '0001' abap_field = 'ProductSalesOrg'              json_field = 'ProductSalesOrg' )
        ( mapping_code = '0001' abap_field = 'ProductDistributionChnl'      json_field = 'ProductDistributionChnl' )
        ( mapping_code = '0001' abap_field = 'MinimumOrderQuantity'         json_field = 'MinimumOrderQuantity' )
        ( mapping_code = '0001' abap_field = 'SupplyingPlant'               json_field = 'SupplyingPlant' )
        ( mapping_code = '0001' abap_field = 'SalesMeasureUnit'             json_field = 'SalesMeasureUnit' )
        ( mapping_code = '0001' abap_field = 'DeliveryQuantityUnit'         json_field = 'DeliveryQuantityUnit' )
        ( mapping_code = '0001' abap_field = 'DeliveryQuantity'             json_field = 'DeliveryQuantity' )
        ( mapping_code = '0001' abap_field = 'DeliveryNoteProcMinDelivQty'  json_field = 'DeliveryNoteProcMinDelivQty' )
        ( mapping_code = '0001' abap_field = 'ProductSalesStatus'           json_field = 'ProductSalesStatus' )
        ( mapping_code = '0001' abap_field = 'ProductSalesStatusValidityDate' json_field = 'ProductSalesStatusValidityDate' )
        ( mapping_code = '0001' abap_field = 'PriceSpecificationProductGroup' json_field = 'PriceSpecificationProductGroup' )
        ( mapping_code = '0001' abap_field = 'AccountDetnProductGroup'      json_field = 'AccountDetnProductGroup' )
        ( mapping_code = '0001' abap_field = 'PricingReferenceProduct'      json_field = 'PricingReferenceProduct' )
        ( mapping_code = '0001' abap_field = 'RoundingProfile'              json_field = 'RoundingProfile' )
        ( mapping_code = '0001' abap_field = 'VolumeRebateGroup'            json_field = 'VolumeRebateGroup' )
        ( mapping_code = '0001' abap_field = 'CashDiscountIsDeductible'     json_field = 'CashDiscountIsDeductible' )
        ( mapping_code = '0001' abap_field = 'ProductCommissionGroup'       json_field = 'ProductCommissionGroup' )
        ( mapping_code = '0001' abap_field = 'LogisticsStatisticsGroup'     json_field = 'LogisticsStatisticsGroup' )
        ( mapping_code = '0001' abap_field = 'VariableSalesUnitIsNotAllowed' json_field = 'VariableSalesUnitIsNotAllowed' )
        ( mapping_code = '0001' abap_field = 'ProductHasAttributeID01'      json_field = 'ProductHasAttributeID01' )
        ( mapping_code = '0001' abap_field = 'ProductHasAttributeID02'      json_field = 'ProductHasAttributeID02' )
        ( mapping_code = '0001' abap_field = 'ProductHasAttributeID03'      json_field = 'ProductHasAttributeID03' )
        ( mapping_code = '0001' abap_field = 'ProductHasAttributeID04'      json_field = 'ProductHasAttributeID04' )
        ( mapping_code = '0001' abap_field = 'ProductHasAttributeID05'      json_field = 'ProductHasAttributeID05' )
        ( mapping_code = '0001' abap_field = 'ProductHasAttributeID06'      json_field = 'ProductHasAttributeID06' )
        ( mapping_code = '0001' abap_field = 'ProductHasAttributeID07'      json_field = 'ProductHasAttributeID07' )
        ( mapping_code = '0001' abap_field = 'ProductHasAttributeID08'      json_field = 'ProductHasAttributeID08' )
        ( mapping_code = '0001' abap_field = 'ProductHasAttributeID09'      json_field = 'ProductHasAttributeID09' )
        ( mapping_code = '0001' abap_field = 'ProductHasAttributeID10'      json_field = 'ProductHasAttributeID10' )
        ( mapping_code = '0001' abap_field = 'ProdIsEntlmntRlvt'            json_field = 'ProdIsEntlmntRlvt' )
        ( mapping_code = '0001' abap_field = 'ProdExtAssortmentPriority'    json_field = 'ProdExtAssortmentPriority' )
        ( mapping_code = '0001' abap_field = 'AssortmentGrade'              json_field = 'AssortmentGrade' )
        ( mapping_code = '0001' abap_field = 'StoreListingProcedure'        json_field = 'StoreListingProcedure' )
        ( mapping_code = '0001' abap_field = 'DistrCenterListingProcedure'  json_field = 'DistrCenterListingProcedure' )
        ( mapping_code = '0001' abap_field = 'StoreListingStartDate'        json_field = 'StoreListingStartDate' )
        ( mapping_code = '0001' abap_field = 'StoreListingEndDate'          json_field = 'StoreListingEndDate' )
        ( mapping_code = '0001' abap_field = 'DistrCenterListingStartDate'  json_field = 'DistrCenterListingStartDate' )
        ( mapping_code = '0001' abap_field = 'DistrCenterListingEndDate'    json_field = 'DistrCenterListingEndDate' )
        ( mapping_code = '0001' abap_field = 'StoreSaleStartDate'           json_field = 'StoreSaleStartDate' )
        ( mapping_code = '0001' abap_field = 'StoreSaleEndDate'             json_field = 'StoreSaleEndDate' )
        ( mapping_code = '0001' abap_field = 'DistrCenterSaleStartDate'     json_field = 'DistrCenterSaleStartDate' )
        ( mapping_code = '0001' abap_field = 'DistributionCenterSaleEndDate' json_field = 'DistributionCenterSaleEndDate' )
        ( mapping_code = '0001' abap_field = 'ProductUnitGroup'             json_field = 'ProductUnitGroup' )
        ( mapping_code = '0001' abap_field = 'StoreOrderMaxDelivQty'        json_field = 'StoreOrderMaxDelivQty' )
        ( mapping_code = '0001' abap_field = 'PriceFixingCategory'          json_field = 'PriceFixingCategory' )
        " ── _ProductSales ─────────────────────────────────────────────────
        ( mapping_code = '0001' abap_field = '_ProductSales'                json_field = '_ProductSales' )
        ( mapping_code = '0001' abap_field = 'SalesStatus'                  json_field = 'SalesStatus' )
        ( mapping_code = '0001' abap_field = 'SalesStatusValidityDate'      json_field = 'SalesStatusValidityDate' )
        ( mapping_code = '0001' abap_field = 'TransportationGroup'          json_field = 'TransportationGroup' )
        ( mapping_code = '0001' abap_field = 'LoadingGroup'                 json_field = 'LoadingGroup' )
        ( mapping_code = '0001' abap_field = 'PackagingProductType'         json_field = 'PackagingProductType' )
        ( mapping_code = '0001' abap_field = 'AllowedPackagingWeightQty'    json_field = 'AllowedPackagingWeightQty' )
        ( mapping_code = '0001' abap_field = 'AllowedPackagingWeightQtyUnit' json_field = 'AllowedPackagingWeightQtyUnit' )
        ( mapping_code = '0001' abap_field = 'AllowedPackagingVolumeQty'    json_field = 'AllowedPackagingVolumeQty' )
        ( mapping_code = '0001' abap_field = 'AllowedPackagingVolumeQtyUnit' json_field = 'AllowedPackagingVolumeQtyUnit' )
        ( mapping_code = '0001' abap_field = 'MaximumLevelByVolumeInPercent' json_field = 'MaximumLevelByVolumeInPercent' )
        ( mapping_code = '0001' abap_field = 'ExcessWeightToleranceValue'   json_field = 'ExcessWeightToleranceValue' )
        ( mapping_code = '0001' abap_field = 'ProdExcessVolumeToleranceValue' json_field = 'ProdExcessVolumeToleranceValue' )
        ( mapping_code = '0001' abap_field = 'PackggProductIsClosedPackaging' json_field = 'PackggProductIsClosedPackaging' )
        ( mapping_code = '0001' abap_field = 'ProductStackingFactor'        json_field = 'ProductStackingFactor' )
        ( mapping_code = '0001' abap_field = 'ProductTaxClassification'     json_field = 'ProductTaxClassification' )
        " ── _ProductQualityManagement ─────────────────────────────────────
        ( mapping_code = '0001' abap_field = '_ProductQualityManagement'    json_field = '_ProductQualityManagement' )
        ( mapping_code = '0001' abap_field = 'QltyMgmtInProcmtIsActive'     json_field = 'QltyMgmtInProcmtIsActive' )
        ( mapping_code = '0001' abap_field = 'CatalogProfile'               json_field = 'CatalogProfile' )
        " ── _ProductPurchaseOrderText ─────────────────────────────────────
        ( mapping_code = '0001' abap_field = '_ProductPurchaseOrderText'    json_field = '_ProductPurchaseOrderText' )
        ( mapping_code = '0001' abap_field = 'TextObjectType'               json_field = 'TextObjectType' )
        ( mapping_code = '0001' abap_field = 'Language'                     json_field = 'Language' )
        ( mapping_code = '0001' abap_field = 'ProductLongText'              json_field = 'ProductLongText' )
        " ── _ProductProcurement ───────────────────────────────────────────
        ( mapping_code = '0001' abap_field = '_ProductProcurement'          json_field = '_ProductProcurement' )
        ( mapping_code = '0001' abap_field = 'PurchaseOrderQuantityUnit'    json_field = 'PurchaseOrderQuantityUnit' )
        ( mapping_code = '0001' abap_field = 'VarblPurOrdUnitStatus'        json_field = 'VarblPurOrdUnitStatus' )
        ( mapping_code = '0001' abap_field = 'PurchasingAcknProfile'        json_field = 'PurchasingAcknProfile' )
        ( mapping_code = '0001' abap_field = 'SourceOfSupplyCategory'       json_field = 'SourceOfSupplyCategory' )
        ( mapping_code = '0001' abap_field = 'ProcurementRule'              json_field = 'ProcurementRule' )
        ( mapping_code = '0001' abap_field = 'PurchasingGroup'              json_field = 'PurchasingGroup' )
        " ── _ProductPlant ─────────────────────────────────────────────────
        ( mapping_code = '0001' abap_field = '_ProductPlant'                json_field = '_ProductPlant' )
        ( mapping_code = '0001' abap_field = 'Plant'                        json_field = 'Plant' )
        ( mapping_code = '0001' abap_field = 'ProfileCode'                  json_field = 'ProfileCode' )
        ( mapping_code = '0001' abap_field = 'ProfileValidityStartDate'     json_field = 'ProfileValidityStartDate' )
        ( mapping_code = '0001' abap_field = 'FiscalYearVariant'            json_field = 'FiscalYearVariant' )
        ( mapping_code = '0001' abap_field = 'PeriodType'                   json_field = 'PeriodType' )
        ( mapping_code = '0001' abap_field = 'ProfitCenter'                 json_field = 'ProfitCenter' )
        ( mapping_code = '0001' abap_field = 'ConfigurableProduct'          json_field = 'ConfigurableProduct' )
        ( mapping_code = '0001' abap_field = 'StockDeterminationGroup'      json_field = 'StockDeterminationGroup' )
        ( mapping_code = '0001' abap_field = 'IsNegativeStockAllowed'       json_field = 'IsNegativeStockAllowed' )
        ( mapping_code = '0001' abap_field = 'ProductCFOPCategory'          json_field = 'ProductCFOPCategory' )
        ( mapping_code = '0001' abap_field = 'ProductIsExciseTaxRelevant'   json_field = 'ProductIsExciseTaxRelevant' )
        ( mapping_code = '0001' abap_field = 'DistrCntrDistributionProfile' json_field = 'DistrCntrDistributionProfile' )
        ( mapping_code = '0001' abap_field = 'ProductIsCriticalPrt'         json_field = 'ProductIsCriticalPrt' )
        ( mapping_code = '0001' abap_field = 'ProductLogisticsHandlingGroup' json_field = 'ProductLogisticsHandlingGroup' )
        ( mapping_code = '0001' abap_field = 'ProductFreightGroup'          json_field = 'ProductFreightGroup' )
        ( mapping_code = '0001' abap_field = 'OriginalBatchReferenceProduct' json_field = 'OriginalBatchReferenceProduct' )
        ( mapping_code = '0001' abap_field = 'ProductMinControlTemperature'  json_field = 'ProductMinControlTemperature' )
        ( mapping_code = '0001' abap_field = 'ProductMaxControlTemperature'  json_field = 'ProductMaxControlTemperature' )
        ( mapping_code = '0001' abap_field = 'ProductControlTemperatureUnit' json_field = 'ProductControlTemperatureUnit' )
        " ── _ProductInternalComment / _ProductInspectionText ──────────────
        ( mapping_code = '0001' abap_field = '_ProductInternalComment'      json_field = '_ProductInternalComment' )
        ( mapping_code = '0001' abap_field = '_ProductInspectionText'       json_field = '_ProductInspectionText' )
        " ── _ProductEWMWarehouse ──────────────────────────────────────────
        ( mapping_code = '0001' abap_field = '_ProductEWMWarehouse'         json_field = '_ProductEWMWarehouse' )
        ( mapping_code = '0001' abap_field = 'EWMWarehouse'                 json_field = 'EWMWarehouse' )
        ( mapping_code = '0001' abap_field = 'EntitledToDisposeParty'       json_field = 'EntitledToDisposeParty' )
        ( mapping_code = '0001' abap_field = 'ProductInternalUUID'          json_field = 'ProductInternalUUID' )
        ( mapping_code = '0001' abap_field = 'SupplyChainUnitUUID'          json_field = 'SupplyChainUnitUUID' )
        ( mapping_code = '0001' abap_field = 'EWMPartyEntitledToDisposeUUID' json_field = 'EWMPartyEntitledToDisposeUUID' )
        ( mapping_code = '0001' abap_field = 'EWMProductProcessBlockProfile' json_field = 'EWMProductProcessBlockProfile' )
        ( mapping_code = '0001' abap_field = 'EWMProcessTypeControlCode'    json_field = 'EWMProcessTypeControlCode' )
        ( mapping_code = '0001' abap_field = 'EWMProductLoadCategory'       json_field = 'EWMProductLoadCategory' )
        ( mapping_code = '0001' abap_field = 'EWMStggAreaDeterminationGroup' json_field = 'EWMStggAreaDeterminationGroup' )
        ( mapping_code = '0001' abap_field = 'EWMIsCnsmpnRlvtForValAddedSrvc' json_field = 'EWMIsCnsmpnRlvtForValAddedSrvc' )
        ( mapping_code = '0001' abap_field = 'RequiredMinShelfLife'         json_field = 'RequiredMinShelfLife' )
        ( mapping_code = '0001' abap_field = 'EWMPtwyControlStrategy'       json_field = 'EWMPtwyControlStrategy' )
        ( mapping_code = '0001' abap_field = 'EWMStorageSectionMethod'      json_field = 'EWMStorageSectionMethod' )
        ( mapping_code = '0001' abap_field = 'EWMStorageBinType'            json_field = 'EWMStorageBinType' )
        ( mapping_code = '0001' abap_field = 'EWMBulkStorageMethod'         json_field = 'EWMBulkStorageMethod' )
        ( mapping_code = '0001' abap_field = 'EWMStockRemovalControlStrategy' json_field = 'EWMStockRemovalControlStrategy' )
        ( mapping_code = '0001' abap_field = 'EWMStockDeterminationGroup'   json_field = 'EWMStockDeterminationGroup' )
        ( mapping_code = '0001' abap_field = 'EWMProdTwoStepPickingRelevant' json_field = 'EWMProdTwoStepPickingRelevant' )
        ( mapping_code = '0001' abap_field = 'EWMSltgRequirementQuantity'   json_field = 'EWMSltgRequirementQuantity' )
        ( mapping_code = '0001' abap_field = 'EWMSltgNumberOfSalesOrderItems' json_field = 'EWMSltgNumberOfSalesOrderItems' )
        ( mapping_code = '0001' abap_field = 'EWMSltgRecmddStorageQuantity'  json_field = 'EWMSltgRecmddStorageQuantity' )
        ( mapping_code = '0001' abap_field = 'EWMSlottingWeightSizeCode'    json_field = 'EWMSlottingWeightSizeCode' )
        ( mapping_code = '0001' abap_field = 'EWMSlottingVolumeSizeCode'    json_field = 'EWMSlottingVolumeSizeCode' )
        ( mapping_code = '0001' abap_field = 'EWMSlottingLengthSizeCode'    json_field = 'EWMSlottingLengthSizeCode' )
        ( mapping_code = '0001' abap_field = 'EWMSlottingWidthSizeCode'     json_field = 'EWMSlottingWidthSizeCode' )
        ( mapping_code = '0001' abap_field = 'EWMSlottingHeightSizeCode'    json_field = 'EWMSlottingHeightSizeCode' )
        ( mapping_code = '0001' abap_field = 'EWMPhysInventoryCountingCycle' json_field = 'EWMPhysInventoryCountingCycle' )
        ( mapping_code = '0001' abap_field = 'EWMProdBackflushWthdrwlMethod' json_field = 'EWMProdBackflushWthdrwlMethod' )
        ( mapping_code = '0001' abap_field = 'EWMKitQuantityCorrelation'    json_field = 'EWMKitQuantityCorrelation' )
        ( mapping_code = '0001' abap_field = 'EWMQuantityAdjustmentProfile'  json_field = 'EWMQuantityAdjustmentProfile' )
        ( mapping_code = '0001' abap_field = 'EWMMrchdsDistrQtyClassfctn'   json_field = 'EWMMrchdsDistrQtyClassfctn' )
        ( mapping_code = '0001' abap_field = 'EWMPreferredUnit'             json_field = 'EWMPreferredUnit' )
        ( mapping_code = '0001' abap_field = 'EWMQualityInspectionGroup'    json_field = 'EWMQualityInspectionGroup' )
        " ── _ProductDescription ───────────────────────────────────────────
        ( mapping_code = '0001' abap_field = '_ProductDescription'          json_field = '_ProductDescription' )
        ( mapping_code = '0001' abap_field = 'ProductDescription'           json_field = 'ProductDescription' )
        " ── _ProductChangeMaster ──────────────────────────────────────────
        ( mapping_code = '0001' abap_field = '_ProductChangeMaster'         json_field = '_ProductChangeMaster' )
        ( mapping_code = '0001' abap_field = 'ChangeNumber'                 json_field = 'ChangeNumber' )
        ( mapping_code = '0001' abap_field = 'RevisionLevel'                json_field = 'RevisionLevel' )
        " ── _ProductBasicText ─────────────────────────────────────────────
        ( mapping_code = '0001' abap_field = '_ProductBasicText'            json_field = '_ProductBasicText' )
    ).

    LOOP AT ldt_data ASSIGNING FIELD-SYMBOL(<L_S_data>).
      TRY.
          <l_s_data>-mapping_uuid = cl_system_uuid=>create_uuid_x16_static( ).
        CATCH cx_uuid_error.
          "handle exception
          out->write( 'Generate UUID error' ).
      ENDTRY.
    ENDLOOP.

    INSERT zw00117t_vn FROM TABLE @ldt_data.
    IF sy-subrc = 0.
      out->write( 'Generate Successful' ).
    ENDIF.
  ENDMETHOD.
ENDCLASS.
